### ISSUE TITLE
1주차 진행 

### ISSUE THREAD

**Issue by bbhye1** [CodeSoom/project-react-2-bbhye1#1]
**1. 이 앱을 언제 사용하나요?**
  기분에 맞게 추천된 장르의 음악을 듣고 싶을 때 사용합니다. 

**2. 제약 조건은 무엇인가요?**
 사용자가 그때 그때의  차분한 <->신나는, 밝은<->어두운 두가지 기분의 정도를 컨트롤러에 체크합니다. 
 사용자의 기분에 맞는 장르 카테고리를 추천해줍니다. 
 원하는 카테고리를 클릭 해 플레이리스트들을 실행시켜줍니다.  
 

**3. 구체적인 사례는 무엇인가요?**
 오늘 사용자는 기분이 매우 좋은 상태로 일에 집중하면서 노래를 듣기 위해 무드 플레이 앱을 사용합니다. 
 사용자는 밝은 느낌이지만 집중하기 위해 차분한 노래를 듣고 싶어 무드를 '차분한'과 '밝은'을 높게 표시하고 play your 
 mood 버튼을 클릭합니다.  
'차분한'과 '밝은'으로 이루어진 음악 장르들을 추천받아 그중 '가사가 없는' 태그가 있는 '로파이' 장르를 선택해 클릭합니다. 
그러면 로파이 장르의 첫번째 플레이리스트가 자동으로 재생되고 화면에는 로파이 장르의 다른 플레이 리스트들이 보여져서 
다음 플레이 리스트로 넘거가거나 특정한 다른 플레이 리스트를 선택 해서 재생할 수 있게 됩니다. 

**4. 이번주에 구현 할 기능을 우선 순위대로 작성해 주세요.**

1. - [x] 개발환경 세팅하기
2. 무드 컨트롤러 페이지 구현하기 
- [ ]  사용자가 클릭한 무드를  퍼센트로 계산하는 로직 구현하기. 
- [ ]  화면 리사이즈 해도 에러가 발생하지 않도록 반응형으로 변경하기. 

3. 카테고리 페이지 
- [ ] 카테고리 데이터 작성하기 - json 파일로 따로 저장하기 -
- [x] 컨트롤러에서 선택한 무드에 맞는 태그들을 가진 장르 카테고리들을 화면에 보여주기
- [ ] 선택한 장르 카테고리를 선택하는 기능 구현하기 

4. 플레이리스트 페이지 
- [ ] fixture로 플레이 리스트들과 현재 재생중인 플레이 리스트 구현하기  
- [ ] 다른 플레이 리스트를 선택하여 재생하는 기능 구현하기. 

![1주차 기획](https://user-images.githubusercontent.com/65213094/99225711-d3613500-282b-11eb-89ad-13294d6eaf74.jpg)

**이후 작업할 내용** 

- 플레이 리스트 컨트롤러 만들기
- 플레이 리스트 저장 기능과 공유버튼 만들기 
- 유튜브 api 사용하여 선택한 카테고리에 맞는 실제 플레이리스트들을 생성하기
- 저장된 플레이 리스트 페이지 만들기
- 재생했던 플레이 리스트 기록 페이지 만들기 
- 플레이 리스트 검색 페이지 만들기  
- 디자인 적용 & 반응형 요소 넣기

**Comment by wholemann** [comment]
컨셉이 명확해서 좋네요. 이번주에 당장 출시하는 걸 목표로 기능을 추려보셔요ㅎㅎ

**Comment by bbhye1** [comment]
**1주차 구현 현황** 

- 선택한 무드의 퍼센트를 구해서 동작하는 것이 아닌 무드를 선택하고 그것에 따른 카테고리를 보여주는 것으로 변경했습니다. 

![20201121](https://user-images.githubusercontent.com/65213094/99937066-167d5400-2da8-11eb-8d8d-5ab9384dfd7b.gif)
