### ISSUE TITLE
모두 모르겠어요를 클릭했을 때 아무것도 나오지 않아요.

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-bbhye1#26]
랜덤으로 틀어줄거라고 생각했는데 다른 의도가 있는건가요?

**Comment by bbhye1** [comment]
아직 구현하지 못한 부분입니다. 지금 작업이 끝나는 대로 반영하겠습니다 😄

**Comment by bbhye1** [comment]
모두 모르겠어요를 두개 다 선택하거나 아무것도 선택하지 않은 경우 랜덤으로 무드 하나를 선정하여 해당 카테고리들을 보여주도록 변경했습니다. 

![Uploading 랜덤카테고리.gif…]()
