### ISSUE TITLE
음악을 클릭하면 스크롤이 이상해져요

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-bbhye1#36]
![image](https://user-images.githubusercontent.com/14071105/100542555-083ea480-328e-11eb-912e-79195bcc8b13.png)

위에가 짤립니다.

**Comment by bbhye1** [comment]
네 ㅜㅜ css를 수정하겠습니다!

**Comment by bbhye1** [comment]
#39 

스크롤이 가능하도록 변경했습니다! 😄
