### ISSUE TITLE
음악 재생 화면이 스크롤에 따라 따라다니면 어떨까요?

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-bbhye1#37]
스크롤 하면 화면이 안보여서 아쉬워요

**Comment by bbhye1** [comment]
이 부분도 css 수정하겠습니다!

**Comment by bbhye1** [comment]
#38 
뮤직 플레이어가 옆에 고정되어 있는 것으로 변경했습니다 😄  
![screencapture-localhost-8080-project-react-2-bbhye1-moodplay-2020-11-30-09_47_38](https://user-images.githubusercontent.com/65213094/100558371-87b18f80-32f1-11eb-8eb4-a70f2daa04fc.jpg)
