### ISSUE TITLE
리스트에서 썸네일의 위치가 고정되어있으면 좋을 것 같아요~

### ISSUE THREAD

**Issue by Kihyun92** [CodeSoom/project-react-2-bbhye1#61]
![image](https://user-images.githubusercontent.com/35797540/101284991-4441ae80-3826-11eb-8706-f402c242f86e.png)
현재는 위와 같이 'justify-content: center' 속성으로 인해 리스트 내 각 아이템 별로 썸네일 위치가 다르게 보여요~ 확인 부탁드립니다 ☺️

**Comment by bbhye1** [comment]
디자인 적용하면서 수정하겠습니다. 😄 👍
