### ISSUE TITLE
페이지를 이동할 때 음악이 정지됩니다.

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-bbhye1#69]
홈에서 음악을 재생하고 있을 때 음악이 정지됩니다.
페이지를 이동하더라도 음악이 계속 재생되고 있으면 좋을 것 같습니다.

**Comment by bbhye1** [comment]
[#78 ](url) 페이지를 이동할 때 음악 끊김현상을 개선했습니다 😄
