### ISSUE TITLE
현재 내가 어디 페이지에 있는지 보이면 좋을 것 같아요

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-bbhye1#77]
![image](https://user-images.githubusercontent.com/14071105/101779738-02bc4680-3b39-11eb-9444-05c43734f2e3.png)

현재 내가 있는 페이지에 하이라이팅을 해주는건 어떨까요?

**Comment by bbhye1** [comment]
[#80 ](url) 
아이콘의 변화를 주어 현재 내가 있는 페이지를 확인 할 수 있도록 수정했습니다.
